# Generated by Django 5.1.15 on 2026-04-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('resource_pattern', models.CharField(help_text='Glob or regex key for resource', max_length=256)),
                ('actions', models.JSONField(default=list, help_text='Allowed actions, e.g. read, write, execute')),
                ('roles', models.JSONField(default=list, help_text='Roles or principals allowed')),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=64, unique=True)),
                ('actor', models.CharField(blank=True, default='', max_length=256)),
                ('action', models.CharField(max_length=128)),
                ('resource', models.CharField(max_length=512)),
                ('allowed', models.BooleanField()),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=128, unique=True)),
                ('algorithm', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('active', 'Active'), ('rotating', 'Rotating'), ('retired', 'Retired')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('quarantined', 'Quarantined'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('source_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
