# Generated by Django 5.1.15 on 2026-04-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloneInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clone_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('template_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('ready', 'Ready'), ('failed', 'Failed'), ('decommissioned', 'Decommissioned')], default='provisioning', max_length=32)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(db_index=True, max_length=128)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=8)),
                ('success', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(max_length=128, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='reproductive.cloneinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
