# Generated by Django 5.1.15 on 2026-04-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('root_path', models.CharField(help_text='Absolute or workspace-relative root', max_length=512)),
                ('kind', models.CharField(choices=[('app', 'Application'), ('library', 'Library'), ('monorepo', 'Monorepo'), ('tooling', 'Tooling')], default='app', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('source_path', models.CharField(help_text='Directory containing template files', max_length=512)),
                ('variables_schema', models.JSONField(default=dict, help_text='JSON schema or list of expected template variables')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('project', 'Project')], default='global', max_length=16)),
                ('key', models.CharField(db_index=True, max_length=256)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_entries', to='skeleton.project')),
            ],
            options={
                'ordering': ['scope', 'key'],
                'indexes': [models.Index(fields=['scope', 'key'], name='skeleton_co_scope_da1694_idx')],
            },
        ),
    ]
