# Generated by Django 5.1.15 on 2026-04-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='ok', max_length=16)),
                ('stream_name', models.CharField(default='', max_length=256)),
                ('pending_events_estimate', models.IntegerField(default=0)),
                ('subscribers_wildcard', models.IntegerField(default=0, help_text="Handlers registered on '*' at sample time")),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=256)),
                ('source_organ', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('routing_meta', models.JSONField(blank=True, default=dict, help_text='Optional bus metadata: stream id, consumer group, etc.')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', '-received_at'], name='heart_event_event_t_8245ad_idx'), models.Index(fields=['source_organ', '-received_at'], name='heart_event_source__bfb04b_idx')],
            },
        ),
    ]
