# Generated by Django 5.1.15 on 2026-04-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(choices=[('teams', 'Microsoft Teams'), ('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('other', 'Other')], default='other', max_length=32)),
                ('external_ref', models.CharField(blank=True, default='', help_text='Provider meeting id, drive file id, etc.', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('recording', 'Recording'), ('transcript', 'Transcript'), ('chat', 'Chat Log'), ('file', 'Generic File'), ('other', 'Other')], default='file', max_length=32)),
                ('logical_name', models.CharField(max_length=512)),
                ('storage_path', models.CharField(help_text='Local or blob URI', max_length=1024)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='lungs.ingestionjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
