# Generated by Django 5.1.15 on 2026-04-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('source_uri', models.CharField(help_text='Path, URL, or blob reference', max_length=1024)),
                ('format', models.CharField(help_text='vtt, srt, pdf, eml, ...', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(default=dict, help_text='Counts, timings, adapter metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransformationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_type', models.CharField(help_text='map, filter, enrich, validate', max_length=64)),
                ('config', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('entity', 'Entity'), ('fact', 'Fact'), ('summary', 'Summary'), ('transcript_chunk', 'Transcript Chunk')], default='fact', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('content', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='digestive_system.processingjob')),
            ],
            options={
                'verbose_name_plural': 'Extracted knowledge',
                'ordering': ['-created_at'],
            },
        ),
    ]
