# Generated by Django 5.1.15 on 2026-04-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('action_type', models.CharField(help_text='Logical action key, e.g. shell.run, github.pr.create', max_length=64)),
                ('payload', models.JSONField(default=dict, help_text='Structured parameters for adapters')),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('source_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('decision_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=64, unique=True)),
                ('agent_name', models.CharField(max_length=128)),
                ('capability', models.CharField(help_text='What the agent was asked to do', max_length=128)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('output_snapshot', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=16)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to='hands.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=64, unique=True)),
                ('adapter', models.CharField(help_text='Adapter that performed the work', max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('rolled_back', 'Rolled Back'), ('skipped', 'Skipped')], max_length=16)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='hands.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
