# Generated by Django 5.1.15 on 2026-04-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('outlook_calendar', 'Outlook Calendar'), ('google_calendar', 'Google Calendar'), ('webhook_generic', 'Generic Webhook'), ('teams_subscription', 'Teams Subscription')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific: calendar id, resource URL, filters')),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.CharField(max_length=64, unique=True)),
                ('signal_type', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('published', 'Published'), ('ignored', 'Ignored'), ('error', 'Error')], default='new', max_length=16)),
                ('bus_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='ears.listener')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
