# Generated by Django 5.1.15 on 2026-04-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=64, unique=True)),
                ('context', models.TextField(help_text='What triggered this decision')),
                ('reasoning', models.TextField(help_text='Chain-of-thought reasoning')),
                ('action', models.TextField(help_text='The decided action')),
                ('confidence', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='pending', max_length=16)),
                ('source_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('model_used', models.CharField(default='', max_length=64)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('template', models.TextField(help_text='Jinja2-style template with {{variables}}')),
                ('category', models.CharField(default='general', max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReasoningChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('model_used', models.CharField(max_length=64)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_steps', to='brain.decision')),
            ],
            options={
                'ordering': ['decision', 'step_number'],
                'unique_together': {('decision', 'step_number')},
            },
        ),
    ]
